### PR TITLE
Update to 8.3.0 + add bump workflow

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
* No effects on the test results from the updating to 8.3.0

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Should expected failures be less than 18?
If I read cron right it is every 15 hours? Is that what you want?

**Comment by IgorTodorovskiIBM** [comment]
> Should expected failures be less than 18? If I read cron right it is every 15 hours? Is that what you want?

We can probably bump it up to hourly for the core tools. I'm not sure if there's any github action resource limits/caps, but we can try. @v1gnesh FYI.

**Comment by v1gnesh** [comment]
@MikeFultonDev - currently, the cron schedule is just a random pick, 15:00 UTC every day.
The Action takes less than a minute so we'll be fine running it every hour.

**Comment by MikeFultonDev** [comment]
> > Should expected failures be less than 18? If I read cron right it is every 15 hours? Is that what you want?
> 
> We can probably bump it up to hourly for the core tools. I'm not sure if there's any github action resource limits/caps, but we can try. @v1gnesh FYI.

What about the number of test failures? I thought it was less than 18?

**Comment by v1gnesh** [comment]
Do ignore if I'm stating the obvious (and missing something)...  

curl 8.2.1:
**Test Status:** Green (1239 tests pass out of 1244 tests - 99.60% success rate)

curl 8.1.2:
**Test Status:** Green (1233 tests pass out of 1239 tests - 99.52% success rate)

**Comment by IgorTodorovskiIBM** [comment]
I've updated the expected failures to 7 for stable and changed the cron period to hourly

**Review by MikeFultonDev — APPROVED** [review]
LGTM

**Pull request merged**
