### PR TITLE
Add zoslib and gawk as dependencies

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Zoslibport doesn’t seem to have any code in it yet. Does it need to be checked in first?

**Comment by IgorTodorovskiIBM** [comment]
> Zoslibport doesn’t seem to have any code in it yet. Does it need to be checked in first?

Hmm, we do have builds of zoslibport. Can you access https://github.com/ZOSOpenTools/zoslibport/blob/main/buildenv?

**Comment by MikeFultonDev** [comment]
Hi
I see buildenv but it points to code in your repo? Shouldn’t it be in
zosopentools?

**Comment by IgorTodorovskiIBM** [comment]
That's a fork of zoslib that I'm maintaining for OSS.  The original repo is under https://github.com/ibmruntimes/zoslib

**Pull request merged**
